name: The Fourth Page
credit: Mike Riverso
desc: |
  <p><cite>the Fourth Page</cite> generators for World of Dungeons.
  <br/>
  <br/>Licensed under the Creative Commons Attribution 3.0 Unported License. To view a copy
  of this license, visit https://creativecommons.org/licenses/by/3.0/
  </p>
