name: The Perilous Wilds
credit: Jason Lutes
url: "http://lampblackandbrimstone.blogspot.com/"
groups:
  grp1: Creatures
  grp2: Dangers & Discoveries
  grp3: Create & Name
  grp4: NPCs
  grp5: Treasure

