name: The Perilous Wilds
id: perilous_wilds
credit: Jason Lutes
priority: 0
url: "http://lampblackandbrimstone.blogspot.com/"
groups:
  grp1: Creatures
  grp2: Dangers & Discoveries
  grp3: Create & Name
  grp4: NPCs
  grp5: Treasure

