name: The Perilous Wilds
id: perilous_wilds
credit: Jason Lutes
priority: 0
url: "http://lampblackandbrimstone.blogspot.com/"
groups:
  grp1: Dangers & Discoveries
  grp2: Create & Name
  grp3: Creatures
  grp4: NPCs
  grp5: Treasure

