name: Freebooters on the Frontier
credit: Jason Lutes
url: "http://lampblackandbrimstone.blogspot.com/"
desc: |
  <p><strong>Antoine Pempie</strong> - French translation of Freebooters on the Frontier, released
           under Creative Commons Attribution - ShareAlike 3.0 Unported license.﻿</p>
