---
genders:
  male: Male
  female: Female
heritages:
  human: Human
  halfling: Halfling
  dwarf: Dwarf
  elf: Elf
playbooks:
  fighter: Fighter
  thief: Thief
  cleric: Cleric
  magic-user: Magic-User
alignments:
  evil: Evil
  chaotic: Chaotic
  neutral: Neutral
  lawful: Lawful
  good: Good
