name: Stars Without Number
credit: Kevin Crawford / Sine Nomine Publishing
url: "http://www.sinenomine-pub.com/"
desc: |
  The content reproduced here is from the free versions of the core SWN rulebook and supplements.
groups:
  grp1: Aliens, Animals, Worlds…
  grp2: NPCs, Corps, Religions…
  grp3: Names
