name: Stars Without Number
id: stars_without_number
priority: 1
credit: Kevin Crawford / Sine Nomine Publishing
url: "http://www.sinenomine-pub.com/"
attribution: |
  The content reproduced here is from the free versions of the core SWN rulebook and various free supplements.
groups:
  grp1: Aliens, Animals, Worlds…
  grp2: NPCs, Corps, Religions…
  grp3: Names
  grp4: Tech, Architecture…
